#!/usr/bin/env python3
"""
Justify the composite-PD weights (Module A vs Module B) instead of hand-setting them.

Modules A and B are trained on different populations (Home Credit vs Give Me Some
Credit) with no shared borrower, so a single blended weight cannot be *fitted* on a
joint label. This script therefore does the honest thing: it derives the
discrimination-optimal reference from each model's measured power, runs a sensitivity
sweep, and documents the governance operating point. It reads only committed metrics
JSON (no raw data) and regenerates 05_governance/composite_weight_rationale.md.

  python 04_decision_engine/calibrate_weights.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
A = json.loads((ROOT / "01_module_a_application_risk/04_outputs/module_a_metrics.json").read_text())["custom"]
B = json.loads((ROOT / "02_module_b_behavioural_risk/04_outputs/module_b_metrics.json").read_text())["custom"]

OPERATING = {"module_a": 0.60, "module_b": 0.40}   # governance operating point (constants.py)


def share(a, b):
    return a / (a + b), b / (a + b)


def band(pd):
    return 1 if pd < 0.05 else 2 if pd < 0.10 else 3 if pd < 0.20 else 4 if pd < 0.35 else 5


gini_a, gini_b = share(A["gini"], B["gini"])
ks_a, ks_b = share(A["ks"], B["ks"])

# sensitivity: representative (pd_a, pd_b) archetypes across a range of w_a
ARCHETYPES = [
    ("Clean prime", 0.03, 0.02),
    ("Prime thin-file", 0.06, 0.05),
    ("A clean, B stressed", 0.05, 0.20),
    ("A weak, B clean", 0.20, 0.05),
    ("Subprime", 0.25, 0.30),
]
W_GRID = [0.40, 0.50, 0.60, 0.70, 0.80]


def sens_rows():
    rows = []
    for name, pa, pb in ARCHETYPES:
        bands = [band(wa * pa + (1 - wa) * pb) for wa in W_GRID]
        rows.append((name, pa, pb, bands))
    return rows


def build_md():
    hdr = "| Archetype | PD_A | PD_B | " + " | ".join(f"w_a={w:.1f}" for w in W_GRID) + " |"
    sep = "|" + "---|" * (3 + len(W_GRID))
    lines = [hdr, sep]
    for name, pa, pb, bands in sens_rows():
        lines.append(f"| {name} | {pa:.0%} | {pb:.0%} | " + " | ".join(f"Band {b}" for b in bands) + " |")
    table = "\n".join(lines)

    return f"""# Composite Weight Rationale (Module A vs Module B)

*Generated by `04_decision_engine/calibrate_weights.py` from committed model metrics. Do not hand-edit.*

## The constraint
Modules A (Home Credit) and B (Give Me Some Credit) are trained on **different
populations with no shared borrower**, so the composite weight cannot be fitted on a
joint outcome label. There is no honest "trained" weight to report. The weight is a
**governance choice**, and this note makes that choice transparent and defensible.

## Discrimination-optimal reference
If the only goal were discrimination and both signals were always available, the weight
would follow each model's measured power:

| Basis | Module A | Module B |
|-------|----------|----------|
| AUC | {A['auc']:.3f} | {B['auc']:.3f} |
| Gini | {A['gini']:.3f} | {B['gini']:.3f} |
| KS | {A['ks']:.3f} | {B['ks']:.3f} |
| **Gini-share weight** | **{gini_a:.2f}** | **{gini_b:.2f}** |
| **KS-share weight** | **{ks_a:.2f}** | **{ks_b:.2f}** |

On pure discrimination, Module B would carry the larger weight (~0.58-0.60), because the
behavioural signal separates better than the application signal.

## Why the operating point anchors Module A ({OPERATING['module_a']:.2f} / {OPERATING['module_b']:.2f})
Three governance reasons override the raw discrimination tilt at origination:

1. **Availability.** Behavioural history is missing for thin-file and new-to-credit
   applicants. The aggregator already falls back to 100% Module A when B is absent, so a
   B-heavy blend would apply to a shrinking, self-selected subset.
2. **Primacy of the application decision.** At origination the application-time signal is
   the primary basis of the credit decision; the behavioural signal is an overlay that
   sharpens it, not the anchor.
3. **Conservatism.** Over-weighting an overlay that can be stale or sparse is the kind of
   fragility a model-risk review flags. Keeping A primary is the prudent default.

The operating point of **{OPERATING['module_a']:.2f} / {OPERATING['module_b']:.2f}** sits between the
discrimination-optimal (B-heavy) and an A-only fallback: it gives the stronger behavioural
signal real influence (40%) while keeping the always-available application signal primary.

## Sensitivity: decisions are robust to the exact split
Composite risk band for representative applicants as the Module A weight moves from 0.40 to 0.80:

{table}

The band assignment is stable across the 0.50 to 0.70 range for every archetype except
the deliberately divergent cases, which correctly route to manual review rather than a
silent auto-decision. The system is therefore not sensitive to the precise weight, which
is the point of documenting a defensible band rather than claiming a fitted optimum.

## Review trigger
Revisit this weight if either module is retrained, if behavioural-data coverage changes
materially, or once a single joint dataset (same borrowers scored by both signals) becomes
available, at which point the weight can be fitted rather than reasoned.
"""


def main():
    print(f"Gini-share weights : A={gini_a:.2f}  B={gini_b:.2f}")
    print(f"KS-share weights   : A={ks_a:.2f}  B={ks_b:.2f}")
    print(f"Operating point    : A={OPERATING['module_a']:.2f}  B={OPERATING['module_b']:.2f} (A anchored primary)")
    print("\nSensitivity (risk band by w_a):")
    for name, pa, pb, bands in sens_rows():
        print(f"  {name:22s} PD_A={pa:.0%} PD_B={pb:.0%}  " + " ".join(f"{w:.1f}:B{b}" for w, b in zip(W_GRID, bands)))
    out = ROOT / "05_governance/composite_weight_rationale.md"
    out.write_text(build_md(), encoding="utf-8")
    print(f"\nWrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
